public/config.js
src/components/file/CreateFile.vue
src/helpers/index.js
src/helpers/schema.js
src/methods/file-edit-view/init-eox-jsonform.js

https://github.com/user-attachments/assets/d3bba0de-1b36-40c0-a8c1-b892567ae8a5
- Added schema through `schemaMap` instead of `url`.
- Schema will be loaded directly from the `config.js` and make a new file in the session using it.

Feat: Allow schema through schemamap

---

public/config.js
src/api/index.js
src/components/file/CreateFile.vue
src/methods/file-edit-view/post-message.js

- Upload Images using Editor
- Upload Video using Editor 
https://github.com/user-attachments/assets/84bf3e11-1908-41f7-8077-6901c03e8302
https://github.com/user-attachments/assets/87bc9861-eba7-4d58-97c8-4d62604690e0

Feat: Insert image and video through editor

---

src/components/file/ActionTabFileList.vue
src/components/session/ActionList.vue
src/components/session/Actions.vue
src/views/SessionsView.vue

- Remove `:snackbar` props from component and rather than using `const snackbar = inject("set-snackbar");` in each component to avoid multiple loop warnings

Fix: Remove snackbar warning due to wrong property declarartion rather than using inject

---

src/helpers/transform.js
src/views/FileEditView.vue

- Comparing old content JSON's `keys` with the new content JSON's key and then order it accordinly

Fix: order new json keys with old content

---

src/api/session.js

- Removed symbols from branch's slugified name.

Fix: remove symbols from branch's slug name

---

.github/workflows/release-please.yml

Adding missing permission in order to push images (see [related issue](https://github.com/orgs/community/discussions/57724)).

fix(ci): add permission to publish packages to workflow

---

.github/workflows/release-please.yml

This adds using `steps.release.outputs.tag_name` for tagging the image.

fix(ci): use tag_name output for tagging image

---

public/config.js
src/api/session.js
src/enums.js
src/router.js
src/views/FileEditView.vue
src/views/SessionView.vue
src/views/SessionsView.vue
vite.config.js

- Introduced `globalThis.basePath` inside `config.js` to control the base path of git clerk so that it can easily be worked on any root level from `/` to `/some-path/`
Example to set `globalThis.basePath` in `config.js` -
```js
globalThis.basePath = "/";
```
```js
globalThis.basePath = "/git-clerk/";
```
```js
globalThis.basePath = "/some-path/one/two/";
```

fix: deployment in subpath by setting BASE_URL

---

src/views/FileEditView.vue

This takes the entire preview url for the iframe src, in order to be able to point to e.g. externally hosted files.

fix: use raw preview URL in order to be able to display external files

---

src/components/global/Navbar.vue
src/views/SessionView.vue

- Disabled `add`/`edit` button when session is `closed` or `merged`

fix: disable `add`/`edit` button when session is `closed`

---

src/methods/file-edit-view/file-change.js

This prevents reaction to "change" event triggering too soon, as this causes the change detection to misbehave.

fix: prevent premature change event trigger

---

src/components/file/Github.vue
src/components/session/Github.vue

Fix: Github button text 

---

cypress/e2e/files-list.cy.js
public/config.js
src/components/session/Automation.vue
src/helpers/automation.js
src/views/SessionView.vue
src/views/SessionsView.vue

https://github.com/user-attachments/assets/a863526c-c529-4630-ab72-ea85824492c4
- Added `automation` through `url`
- Logics can be added to `config.js` - `globalThis.automation`
- Triggered using these params 
- `session=some-name`
- `automation=automation-id`
- `field1=some-field-value-1`
- `field2=some-field-value-2`
- etc
- URL path `format` 
```
/?session=Name&automation=automation-id&field1=value-field1&field2=value-field2
```

Feat: Automation through outside URL

---

src/components/session/Review.vue

- Fixed: on page load, props was not getting into `watch` function.

fix: review component not getting into watch function on init

---

src/api/session.js

- When a duplicate fork is already present in the same origin account, the github API does not allow forking even with the name change.

Fix: Toast message when a duplicate fork from same origin account exist

---

README.md
public/config.js
src/api/index.js
src/enums.js
src/helpers/automation.js
src/helpers/index.js
src/helpers/schema.js
src/views/SessionView.vue

- Unified all the `globalThis` git clerk related config to `globalThis.gitClerkConfig` and can be accessed as `globalThis.gitClerkConfig.ghConfig`
```js
globalThis.gitClerkConfig = {
ghConfig,
basePath,
schemaMap,
automation,
customEditorInterfaces,
generateEnums,
};
```
- Previously used individual `config` can also be assigned like `globalThis.ghConfig`

Feat: Unified all the `globalThis` git clerk related config to `globalThis.gitClerkConfig`

---

README.md
cypress.config.js
cypress/e2e/files-list.cy.js
public/config.js
src/api/index.js
src/api/session.js
src/components/file/ActionTabFileList.vue
src/components/file/index.js
src/components/session/ActionSessions.vue
src/components/session/ActionTabSession.vue
src/components/session/Delete.vue
src/components/session/DeployedPreview.vue
src/components/session/Github.vue
src/components/session/Rename.vue
src/components/session/Review.vue
src/components/session/index.js
src/enums.js
src/helpers/query-session.js
src/methods/session-view/check-status-method.js
src/methods/session-view/query-session-details.js
src/methods/sessions-view/check-status-method.js
src/views/SessionView.vue

- Added `Deployed Preview` button using `config.js`
- Anyone can enable it by assigning `deployedPreviewLink()` in `config.js` to return a `deployed-preview` link
```js
globalThis.gitClerkConfig = {
[...]
deployedPreviewLink: (sessionDetail) => {
const { number } = sessionDetail;
return `https://deploy-preview-url.com/${number}/preview.html`;
}
[...]
};
```
- Also updated Action Tab style to adjust  action in `session` dropdown menu

Feat: Support preview deployment link 

---

README.md
public/config.js
src/views/FileEditView.vue

- Added `jsonform` option part of `schemaMap`
```
globalThis.gitClerkConfig.schemaMap = [
{
path: "/foo/bar/<id>.json",
schema: {},
content: {},
preview: "/example-preview.html",
jsonform: {
options: {...}
}
},
]
```

feat: override jsonform options

---

src/helpers/automation.js

This adds the ability for the `path` also to be an async function (like `content`).

fix: async path

---

package-lock.json
package.json

This PR updates `eox-jsonform` package, which includes fixes for checkboxes, textareas and tabbed form display.

chore(deps): update eox-jsonform package

---

package-lock.json
package.json

This updates the `eox-jsonform` package, fixing a bug during error validation and tabbed display of the input form.

fix(deps): update package to prevent error with form validation

---

src/components/global/CursorPagination.vue

- Restricting next page number if `hasNextPage` not available

Fix: cursor pagination restricting next page number if `hasNextPage` not available"

---

src/components/file/Rename.vue

https://github.com/user-attachments/assets/7f2d8ecd-da16-4aae-a289-e72d4390f442
- Earlier, it used to route using `window.location.href`, which was causing routing to the wrong page in `inframe` based apps and throwing `404`. Now I have used `vue-router` to route to the correct page.

Fix: Routing issue after renaming
